#!/usr/bin/env bun
// Generates src/skills.generated.ts by reading all skills/*/SKILL.md files.
// Run via `make build` before bun compile so the binary embeds every skill.

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const root = join(import.meta.dir, "..");
const skillsDir = join(root, "skills");
const outFile = join(root, "src", "skills.generated.ts");

const entries = readdirSync(skillsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => {
    const content = readFileSync(join(skillsDir, d.name, "SKILL.md"), "utf8");
    return `  ${JSON.stringify(d.name)}: ${JSON.stringify(content)}`;
  });

const output = `// AUTO-GENERATED by scripts/gen-skills.ts — do not edit by hand.
export const SKILLS: Record<string, string> = {
${entries.join(",\n")},
};
`;

writeFileSync(outFile, output);
console.log(`gen-skills: wrote ${entries.length} skill(s) to src/skills.generated.ts`);
